spring:
  datasource:
    url: jdbc:postgresql://gondola.proxy.rlwy.net:34744/railway?sslmode=require
    username: postgres
    password: okWjPytgftlCFckjWjHQKCljdtdgGmSn
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect